/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_grafica_transporte;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Josema
 */
public class SaldoRecarga extends javax.swing.JFrame {

        // Variable para almacenar el saldo actual
    private int saldo = 0;
    /**
     * Creates new form SaldoRecarga
     */
    public SaldoRecarga() {
          initComponents();
           // Inicializa el saldo en el JLabel
        SaldoLabel.setText(saldo + "€");
        
           //Pongo La imagen para mi icono , y barra de tareas
       setIconImage(new ImageIcon(getClass().getResource("/Imagenes/LOGOBIPICO.jpg")).getImage());
       setTitle("Busly APP");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        LabelSelecciona = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Jlabel3 = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(388, 499));
        setPreferredSize(new java.awt.Dimension(388, 499));
        setSize(new java.awt.Dimension(388, 499));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jPanel1.setMinimumSize(new java.awt.Dimension(388, 499));
        jPanel1.setPreferredSize(new java.awt.Dimension(388, 499));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSelecciona.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        LabelSelecciona.setForeground(new java.awt.Color(12, 121, 168));
        LabelSelecciona.setText("Seleccione el mes para recargar saldo");
        jPanel1.add(LabelSelecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(12, 121, 186));
        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Recargar Saldo");
        jButton1.setActionCommand("jButton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        Jlabel3.setBackground(new java.awt.Color(12, 121, 168));
        Jlabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        Jlabel3.setForeground(new java.awt.Color(12, 121, 168));
        Jlabel3.setText(" Saldo Actual");
        jPanel1.add(Jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, 30));

        SaldoLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        SaldoLabel.setForeground(new java.awt.Color(12, 121, 168));
        SaldoLabel.setText("      0 ");
        jPanel1.add(SaldoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buena2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    // Obtener el mes seleccionado en el JMonthChooser
        int mesSeleccionado = jMonthChooser1.getMonth(); // Obtiene el mes (0 - 11)
        String mesNombre = obtenerNombreMes(mesSeleccionado); // Convertir a nombre de mes

        // Mostrar el JOptionPane con el mensaje de recarga exitosa
        JOptionPane.showMessageDialog(null, "Su abono ha sido recargado correctamente para el mes de: " + mesNombre);
      
        
    
         // Actualizar el saldo
        saldo += 60;

        // Actualizar el JLabel con el nuevo saldo
        SaldoLabel.setText(saldo + "€");

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

 
    
    // Método para convertir el número del mes al nombre correspondiente
// Este método debe estar fuera del ActionListener, pero dentro de la clase
private String obtenerNombreMes(int mes) {
    String[] nombresMeses = {
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
    };
    return nombresMeses[mes]; // Retorna el nombre del mes
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaldoRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaldoRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaldoRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaldoRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaldoRecarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel LabelSelecciona;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
