/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_grafica_transporte;

import interfaz_grafica_transporte.SaldoRecarga;

/**
 *
 * @author HP
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Texto = new javax.swing.JLabel();
        jLabel_Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        menuRecarga = new javax.swing.JMenuItem();
        menuLineas = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();
        menuContacto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Texto.setFont(new java.awt.Font("Arial Nova Cond Light", 1, 12)); // NOI18N
        jLabel_Texto.setText("Porfavor acceda al Menú de \"Saldo y Recarga\"");
        getContentPane().add(jLabel_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 270, 40));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUENA.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 51));
        jMenuBar1.setBorder(null);

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon01.png"))); // NOI18N

        menuRecarga.setText("Saldo y Recarga");
        menuRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecargaActionPerformed(evt);
            }
        });
        jMenu.add(menuRecarga);

        menuLineas.setText("Lineas");
        menuLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLineasActionPerformed(evt);
            }
        });
        jMenu.add(menuLineas);

        menuAcercaDe.setText("Acerca de");
        jMenu.add(menuAcercaDe);

        menuContacto.setText("Contacto");
        jMenu.add(menuContacto);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLineasActionPerformed

    private void menuRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecargaActionPerformed

     SaldoRecarga saldoRecargaFrame = new SaldoRecarga();

        // Hacer visible el nuevo JFrame
        saldoRecargaFrame.setVisible(true);

        // Cerrar el JFrame actual
        dispose();
    



      
    }//GEN-LAST:event_menuRecargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Texto;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenuItem menuContacto;
    private javax.swing.JMenuItem menuLineas;
    private javax.swing.JMenuItem menuRecarga;
    // End of variables declaration//GEN-END:variables
}
